### ISSUE TITLE
Missing logo and warning

### ISSUE THREAD

**Issue by winternewt** [longevity-genie/chat-ui#1]
## Bug description
Missing logo and warning

## Steps to reproduce

Building using Dockerfile as git submodule

## Logs

```
 => ERROR [huggingchat-ui builder 3/3] RUN npm run build                                                                                                                                                            3.0s
------
 > [huggingchat-ui builder 3/3] RUN npm run build:
0.449 
0.449 > chat-ui@0.9.2 build
0.449 > vite build
0.449 
0.570 ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
0.570 
0.570     tsconfig.json:2:12:
0.570       2 │   "extends": "./.svelte-kit/tsconfig.json",
0.570         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0.570 
1.368 vite v5.4.0 building SSR bundle for production...
1.390 transforming...
2.915 ✓ 197 modules transformed.
2.917 x Build failed in 1.55s
2.917 error during build:
2.917 Could not resolve "../../../../../static/huggingchat/logo.png?raw" from "src/routes/assistant/[assistantId]/thumbnail.png/ChatThumbnail.svelte"
2.917 file: /app/src/routes/assistant/[assistantId]/thumbnail.png/ChatThumbnail.svelte
2.917     at getRollupError (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
2.917     at error (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
2.917     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:19213:24)
2.917     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:19173:26
2.939 npm notice
2.939 npm notice New patch version of npm available! 10.8.2 -> 10.8.3
2.939 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
2.939 npm notice To update run: npm install -g npm@10.8.3
2.939 npm notice
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1

```

### Specs

- **OS**: Linux
- **Browser**:
- **chat-ui commit**: [f912f02](https://github.com/longevity-genie/chat-ui/commit/f912f02677750ff2ffd6a8b713aeeda988ba29c2)

**Comment by winternewt** [comment]
WA: cp chat-ui/static/geneticsgenie/logo.png chat-ui/static/huggingchat/

**Comment by marfantyk** [comment]
Apparently in two svelte files this path was hardcoded. I changed that part of the code to dynamic approach with last commit. Could you check if it works for you too please?

**Comment by winternewt** [comment]
Yes, it's fixed and working properly now
